update operations. Fixed error when compiling with PTAM
Caused error in PTAM in combination with cv_bridge in ROS. 
error: missing template arguments before "(" token